// data.js
export const EVENTS = [
  {
    id: 1,
    title: "Modern Web Development Seminar",
    date: "2025-02-10",
    time: "10:00 AM",
    location: "Auditorium, Tech Park",
    locationShort: "Kochi",
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&q=80&w=600",
    category: "Seminars",
    tags: ["Web", "Development", "Seminar"],
    attendees: 120,
    about: "Explore the latest trends in web development with industry experts. Includes hands-on sessions and networking opportunities.",
    prizes: "Certificate of Participation",
    contactEmail: "webseminar@techpark.com",
    contactPhone: "+91-9876543210",
    organizer: "Tech Park Team",
    isFeatured: true
  },
  {
    id: 2,
    title: "Advanced React Workshop",
    date: "2024-12-22",
    time: "02:00 PM",
    location: "Innovation Hub, Tech Center",
    locationShort: "Kochi",
    image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&q=80&w=600",
    category: "Workshops",
    tags: ["React", "Frontend", "Workshop"],
    attendees: 80,
    about: "Deep dive into React hooks, context API, and performance optimization. Includes live coding and Q&A.",
    prizes: "React T-shirt, Certificate",
    contactEmail: "reactworkshop@techcenter.com",
    contactPhone: "+91-9876543211",
    organizer: "React Community",
    isFeatured: false
  },
  {
    id: 3,
    title: "AI in Healthcare Seminar",
    date: "2025-03-15",
    time: "11:30 AM",
    location: "Conference Hall, MedCity",
    locationShort: "Kozhikode",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&q=80&w=600",
    category: "Seminars",
    tags: ["AI", "Healthcare", "Seminar"],
    attendees: 200,
    about: "Discover how artificial intelligence is transforming healthcare. Keynotes from doctors and data scientists.",
    prizes: "Best Question Award",
    contactEmail: "aihealth@medcity.com",
    contactPhone: "+91-9876543212",
    organizer: "MedCity Research",
    isFeatured: false
  },
  {
    id: 4,
    title: "Cloud Computing Workshop",
    date: "2025-01-25",
    time: "09:00 AM",
    location: "Lab 3, IT Campus",
    locationShort: "Kollam",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&q=80&w=600",
    category: "Workshops",
    tags: ["Cloud", "AWS", "Workshop"],
    attendees: 60,
    about: "Hands-on workshop on AWS, Azure, and GCP. Learn cloud deployment and scaling techniques.",
    prizes: "Cloud Credits, Certificate",
    contactEmail: "cloudworkshop@itcampus.com",
    contactPhone: "+91-9876543213",
    organizer: "IT Campus",
    isFeatured: true
  },
  {
    id: 5,
    title: "Digital Marketing Seminar",
    date: "2025-04-05",
    time: "03:00 PM",
    location: "Seminar Hall, Biz Center, Alappuzha",
    locationShort: "Alappuzha",
    image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&q=80&w=600",
    category: "Seminars",
    tags: ["Marketing", "Digital", "Seminar"],
    attendees: 150,
    about: "Learn the latest strategies in digital marketing from top professionals. Includes case studies and live demos.",
    prizes: "Marketing Toolkit",
    contactEmail: "marketingseminar@bizcenter.com",
    contactPhone: "+91-9876543214",
    organizer: "Biz Center",
    isFeatured: false
  },
  {
    id: 6,
    title: "UI/UX Design Workshop",
    date: "2025-02-28",
    time: "01:00 PM",
    location: "Design Studio, Creative Hub, Pathanamthitta",
    locationShort: "Pathanamthitta",
    image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&q=80&w=600",
    category: "Workshops",
    tags: ["UI", "UX", "Workshop"],
    attendees: 50,
    about: "Interactive workshop on UI/UX principles, prototyping, and usability testing. Includes portfolio review.",
    prizes: "Design Book, Certificate",
    contactEmail: "uidesign@creativehub.com",
    contactPhone: "+91-9876543215",
    organizer: "Creative Hub",
    isFeatured: false
  }
];